# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: knn 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "knn"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["reddavis"]
  s.date = "2015-11-02"
  s.description = "Simple K Nearest Neighbour algorithm"
  s.email = "reddavis@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/example_one.rb",
    "knn.gemspec",
    "lib/fixed_queue.rb",
    "lib/knn.rb",
    "spec/fixed_len_queue_spec.rb",
    "spec/knn_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/reddavis/knn"
  s.rubygems_version = "2.4.8"
  s.summary = "Simple K Nearest Neighbour algorithm"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<distance_measures>, [">= 0.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<distance_measures>, [">= 0.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<distance_measures>, [">= 0.0.0"])
  end
end

